# Generated by Django 2.2.6 on 2020-05-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSiiFmWzdp-WVoPqwSCfraHDzZMh1AyRnkpxZYr9HynkkS6D39l&usqp=CAU'),
        ),
    ]
