# Generated by Django 2.2.6 on 2019-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191102_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestchoice',
            name='interest',
            field=models.CharField(choices=[('A', 'travelling'), ('B', 'exercise'), ('C', 'going to the theater'), ('D', 'dancing'), ('E', 'cooking'), ('F', 'doing stuff outdoors'), ('G', 'politics'), ('H', 'pets'), ('I', 'photography'), ('J', 'sports'), ('K', 'art'), ('L', 'learning'), ('M', 'music'), ('N', 'comedy'), ('O', 'reading')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
