# Generated by Django 2.2.6 on 2019-12-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191102_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestchoice',
            name='interest',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
